//https://www.youtube.com/watch?v=6Cm31H_zmvM me ayude con este video para hacer el diseno agradable a la vista
//https://flatuicolors.com/palette/gb me ayude de esta pagina para poder configurar los colores (Use una paleta de colores)
//https://www.youtube.com/watch?v=nMhB4EoMm8A usé este video para saber cómo modificar la imagen de los botones
package com.sc403.proyectoprograclientejv;

import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

public class Principal extends javax.swing.JFrame implements Runnable {

    private String hora;
    private String minutos;
    private String segundos;
    private String ampm;
    Calendar calendario;
    Thread h1;

    public Principal() {
        initComponents();
        h1 = new Thread(this);
        h1.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        nombreEmpresa = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_MostrarClientes = new javax.swing.JButton();
        btn_MostrarPlanes = new javax.swing.JButton();
        btn_ModificarCliente = new javax.swing.JButton();
        btn_ModificarPlan = new javax.swing.JButton();
        btn_EliminarCliente = new javax.swing.JButton();
        btn_EliminarPlan = new javax.swing.JButton();
        btn_AgregarCliente = new javax.swing.JButton();
        btn_AgregarPlan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Lbl_Reloj = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();
        btn_chat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(127, 143, 166));

        jPanel2.setBackground(new java.awt.Color(245, 246, 250));

        nombreEmpresa.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        nombreEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        nombreEmpresa.setText("Provedor de Internet y Cable S.M.K.J");

        jPanel3.setBackground(new java.awt.Color(25, 42, 86));

        btn_MostrarClientes.setBackground(new java.awt.Color(25, 42, 86));
        btn_MostrarClientes.setForeground(new java.awt.Color(245, 246, 250));
        btn_MostrarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contents/imgBTN_MostrarClientes.jpg"))); // NOI18N
        btn_MostrarClientes.setBorderPainted(false);
        btn_MostrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MostrarClientesActionPerformed(evt);
            }
        });

        btn_MostrarPlanes.setBackground(new java.awt.Color(25, 42, 86));
        btn_MostrarPlanes.setForeground(new java.awt.Color(245, 246, 250));
        btn_MostrarPlanes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contents/imgBTN_MostrarPlanes.jpg"))); // NOI18N
        btn_MostrarPlanes.setBorderPainted(false);
        btn_MostrarPlanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MostrarPlanesActionPerformed(evt);
            }
        });

        btn_ModificarCliente.setBackground(new java.awt.Color(25, 42, 86));
        btn_ModificarCliente.setForeground(new java.awt.Color(245, 246, 250));
        btn_ModificarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contents/imgBTN_ModificarClientes.jpg"))); // NOI18N
        btn_ModificarCliente.setBorderPainted(false);
        btn_ModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ModificarClienteActionPerformed(evt);
            }
        });

        btn_ModificarPlan.setBackground(new java.awt.Color(25, 42, 86));
        btn_ModificarPlan.setForeground(new java.awt.Color(245, 246, 250));
        btn_ModificarPlan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contents/imgBTN_ModificarPlanes.jpg"))); // NOI18N
        btn_ModificarPlan.setBorderPainted(false);

        btn_EliminarCliente.setBackground(new java.awt.Color(25, 42, 86));
        btn_EliminarCliente.setForeground(new java.awt.Color(245, 246, 250));
        btn_EliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contents/imgBTN_EliminarCliente.jpg"))); // NOI18N
        btn_EliminarCliente.setBorderPainted(false);
        btn_EliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarClienteActionPerformed(evt);
            }
        });

        btn_EliminarPlan.setBackground(new java.awt.Color(25, 42, 86));
        btn_EliminarPlan.setForeground(new java.awt.Color(245, 246, 250));
        btn_EliminarPlan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contents/imgBTN_EliminarPlan.jpg"))); // NOI18N
        btn_EliminarPlan.setBorderPainted(false);
        btn_EliminarPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarPlanActionPerformed(evt);
            }
        });

        btn_AgregarCliente.setBackground(new java.awt.Color(25, 42, 86));
        btn_AgregarCliente.setForeground(new java.awt.Color(245, 246, 250));
        btn_AgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contents/imgBTN_AgregarCliente.jpg"))); // NOI18N
        btn_AgregarCliente.setBorderPainted(false);
        btn_AgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarClienteActionPerformed(evt);
            }
        });

        btn_AgregarPlan.setBackground(new java.awt.Color(25, 42, 86));
        btn_AgregarPlan.setForeground(new java.awt.Color(245, 246, 250));
        btn_AgregarPlan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contents/imgBTN_AgregarPlan.jpg"))); // NOI18N
        btn_AgregarPlan.setBorderPainted(false);
        btn_AgregarPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarPlanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_MostrarPlanes, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_MostrarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ModificarCliente)
                    .addComponent(btn_ModificarPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_EliminarCliente)
                        .addGap(27, 27, 27)
                        .addComponent(btn_AgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_EliminarPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_AgregarPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_EliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_AgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btn_EliminarPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_AgregarPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_MostrarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ModificarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_MostrarPlanes, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ModificarPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contents/LogoEmpresaP.jpg"))); // NOI18N

        Lbl_Reloj.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_Reloj.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Lbl_Reloj.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(351, 351, 351)
                .addComponent(nombreEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lbl_Reloj, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombreEmpresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lbl_Reloj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btn_salir.setBackground(new java.awt.Color(127, 143, 166));
        btn_salir.setForeground(new java.awt.Color(245, 246, 250));
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contents/imgBTN_Salir.jpg"))); // NOI18N
        btn_salir.setBorderPainted(false);
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        btn_chat.setBackground(new java.awt.Color(127, 143, 166));
        btn_chat.setForeground(new java.awt.Color(245, 246, 250));
        btn_chat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contents/imgBTN_Chat.jpg"))); // NOI18N
        btn_chat.setBorderPainted(false);
        btn_chat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btn_chat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_salir)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 454, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_salir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_chat, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MostrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MostrarClientesActionPerformed
        ManejoArchivos objArchivos = new ManejoArchivos();
        objArchivos.mostrar_reporte_de_Clientes();


    }//GEN-LAST:event_btn_MostrarClientesActionPerformed

    private void btn_MostrarPlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MostrarPlanesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_MostrarPlanesActionPerformed

    private void btn_AgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarClienteActionPerformed
        ManejoArchivos objArchivos = new ManejoArchivos();
        Cliente objCliente = new Cliente();
        objCliente.pedir_datos();
        objArchivos.setObj_Cliente(objCliente);
        objArchivos.agregar_persona();
    }//GEN-LAST:event_btn_AgregarClienteActionPerformed

    private void btn_EliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarClienteActionPerformed
        ManejoArchivos objArchivos = new ManejoArchivos();

        objArchivos.borrar_por_Num_contrato();

    }//GEN-LAST:event_btn_EliminarClienteActionPerformed

    private void btn_EliminarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarPlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_EliminarPlanActionPerformed

    private void btn_AgregarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarPlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AgregarPlanActionPerformed

    private void btn_ModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ModificarClienteActionPerformed
        ManejoArchivos objArchivos = new ManejoArchivos();
        objArchivos.Modificar_informacion_del_Cliente();
    }//GEN-LAST:event_btn_ModificarClienteActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_chatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_chatActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_Reloj;
    private javax.swing.JButton btn_AgregarCliente;
    private javax.swing.JButton btn_AgregarPlan;
    private javax.swing.JButton btn_EliminarCliente;
    private javax.swing.JButton btn_EliminarPlan;
    private javax.swing.JButton btn_ModificarCliente;
    private javax.swing.JButton btn_ModificarPlan;
    private javax.swing.JButton btn_MostrarClientes;
    private javax.swing.JButton btn_MostrarPlanes;
    private javax.swing.JButton btn_chat;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel nombreEmpresa;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        Thread ct = Thread.currentThread();

        while (ct == h1) {
            calcula();
            Lbl_Reloj.setText(hora + ":" + minutos + ":" + segundos + ":" + ampm);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
            }

        }
    }
    private void calcula() {
        Calendar calendario = new GregorianCalendar();
        Date fechaHoraActual = new Date();
        calendario.setTime(fechaHoraActual);
        ampm = calendario.get(Calendar.AM_PM) == Calendar.AM ? "AM" : "PM";
        if (ampm.equals("PM")) {
            int h = calendario.get(Calendar.HOUR_OF_DAY) - 12;
            hora = h > 9 ? "" + h : "0" + h;
        } else {
            hora = calendario.get(Calendar.HOUR_OF_DAY) > 9 ? "" + calendario.get(Calendar.HOUR_OF_DAY) : "0" + calendario.get(Calendar.HOUR_OF_DAY);
        }
        minutos = calendario.get(Calendar.MINUTE) > 9 ? "" + calendario.get(Calendar.MINUTE) : "0" + calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND) > 9 ? "" + calendario.get(Calendar.SECOND) : "0" + calendario.get(Calendar.SECOND);
    }
}
